### ISSUE TITLE
ft_memmove

### ISSUE THREAD

**Issue by chi7ed** [wmBolles/LibFt#1]
###  VLAs <h5>Variable-Length Arrays</h5> [ft_memmove.c](https://github.com/wmBolles/LibFt/blob/main/ft_memmove.c)
The use of a variable-length array (temp[n]) is not portable in C. Variable-length arrays were introduced in C99 and are not supported in all C compilers. To fix this, you can allocate memory dynamically using malloc instead.
 
```c
char	  temp[n];
``` 
### Unused Checks 
Checking for null pointers (!dest and !src) and n == 0 is not required because memmove should work with null pointers and zero-length copies. These checks can be removed.

```c
if (!dest || !src) 
		return (NULL)
```

thanks...

**Comment by wmBolles** [comment]
Hi @chi7ed 

Issue fixed! Thanks for reporting it.

Best regards,
@wmBolles
